import { IdbService } from './IdbService';
import { GameService } from './GameService';
import { AudioService } from './AudioService';
import { PlacementService } from './PlacementService';
import { PacksService } from './PacksService';
import { ProgressService } from './ProgressService';
import { I18nService } from './I18nService';
import { LangsService } from './LangsService';
import { ActiveLangsService } from './ActiveLangsService';
import { ActiveLangsStore } from './ActiveLangsStore';
import { ProgressStore } from './ProgressStore';
import { PlacementStore } from './PlacementStore';
import { PacksStore } from './PacksStore';
import { ReportService } from './ReportService';

export const idbServiceInstance         = new IdbService();
export const gameServiceInstance        = new GameService();
export const audioServiceInstance       = new AudioService(idbServiceInstance);
export const placementServiceInstance   = new PlacementService(idbServiceInstance);
export const packsServiceInstance       = new PacksService(idbServiceInstance);
export const progressServiceInstance    = new ProgressService(idbServiceInstance);
export const i18nServiceInstance        = new I18nService();
export const langsServiceInstance       = new LangsService();
export const activeLangsServiceInstance = new ActiveLangsService();
export const activeLangsStoreInstance   = new ActiveLangsStore(activeLangsServiceInstance, idbServiceInstance);
export const progressStoreInstance      = new ProgressStore(progressServiceInstance);
export const placementStoreInstance     = new PlacementStore(placementServiceInstance);
export const packsStoreInstance         = new PacksStore(packsServiceInstance);
export const reportServiceInstance      = new ReportService();

export type { IdbService }         from './IdbService';
export type { GameService }        from './GameService';
export { WIN_TARGET }              from './GameService';
export type { AudioService }       from './AudioService';
export type { PlacementService }   from './PlacementService';
export type { PacksService }       from './PacksService';
export type { InstalledPackInfo }  from './PacksService';
export type { ProgressService }    from './ProgressService';
export type { I18nService }        from './I18nService';
export type { LangsService }       from './LangsService';
export type { ActiveLangsService } from './ActiveLangsService';
export type { ActiveLangsStore }   from './ActiveLangsStore';
export type { ProgressStore }      from './ProgressStore';
export type { PlacementStore }     from './PlacementStore';
export type { PacksStore }         from './PacksStore';
export type { PackPair }           from './PacksStore';
export type { ReportService }      from './ReportService';
